# run again.  Do not edit this file unless you know what you are doing.

from pathlib import Path

from PySide6 import QtCore, QtWidgets
from PySide6.QtCore import QMetaObject, Qt, QTimer
from PySide6.QtGui import QFont, QColor, QPixmap
from PySide6.QtWidgets import QHBoxLayout, QFontDialog, QColorDialog, QLabel, QSlider

from videotrans.configure import config


class Ui_vasrt(object):
    def setupUi(self, vasrt):
        self.has_done = False
        if not vasrt.objectName():
            vasrt.setObjectName(u"vasrt")
        vasrt.resize(1000, 500)
        vasrt.setWindowModality(QtCore.Qt.NonModal)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(vasrt.sizePolicy().hasHeightForWidth())
        vasrt.setSizePolicy(sizePolicy)

        self.horizontalLayout_3 = QHBoxLayout(vasrt)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")

        # start
        self.v3 = QtWidgets.QVBoxLayout()
        self.v3.setObjectName("v3")
        
        # 添加预览区域
        self.preview_label = QLabel()
        self.preview_label.setObjectName("preview_label")
        self.preview_label.setMinimumSize(QtCore.QSize(640, 360))
        self.preview_label.setMaximumSize(QtCore.QSize(640, 360))
        self.preview_label.setAlignment(Qt.AlignCenter)
        self.preview_label.setStyleSheet("background-color: #1a1a1a; border: 1px solid #444;")
        self.preview_label.setText("视频预览区域\n选择视频后将显示字幕效果" if config.defaulelang == 'zh' else "Video Preview Area\nSubtitle effect will be displayed after selecting video")
        self.preview_label.setScaledContents(False)
        self.video_frame_path = None  # 存储视频帧路径
        self.current_video_path = None  # 存储当前视频路径
        self.video_duration_ms = 0  # 视频时长（毫秒）
        self.video_fps = 25  # 视频帧率（默认25fps）
        self.current_time_ms = 0  # 当前时间位置（毫秒）
        self.subtitle_list = []  # 存储字幕列表
        self.current_srt_path = None  # 存储当前字幕文件路径
        
        # 添加防抖定时器
        self.preview_update_timer = QTimer()
        self.preview_update_timer.setSingleShot(True)
        self.preview_update_timer.timeout.connect(self._do_update_preview)
        
        # 添加时间轴滑块
        self.timeline_layout = QtWidgets.QHBoxLayout()
        
        # 当前时间标签
        self.timeline_current_label = QtWidgets.QLabel()
        self.timeline_current_label.setText("00:00:00")
        self.timeline_current_label.setMinimumWidth(70)
        self.timeline_current_label.setAlignment(Qt.AlignCenter)
        
        # 帧数调整设置
        self.frame_step_label = QtWidgets.QLabel()
        self.frame_step_label.setText("步进:" if config.defaulelang == 'zh' else "Step:")
        self.frame_step_label.setToolTip("每次调整的帧数" if config.defaulelang == 'zh' else "Frames to adjust each time")
        
        self.frame_step_input = QtWidgets.QLineEdit()
        self.frame_step_input.setText("1")
        self.frame_step_input.setMaximumWidth(50)
        self.frame_step_input.setAlignment(Qt.AlignCenter)
        self.frame_step_input.setToolTip("输入每次跳转的帧数(1-100)" if config.defaulelang == 'zh' else "Enter frames to skip (1-100)")
        self.frame_step_input.textChanged.connect(self._update_frame_buttons_text)
        
        # 向前N帧按钮
        self.frame_prev_btn = QtWidgets.QPushButton()
        self.frame_prev_btn.setText("◀ -1帧" if config.defaulelang == 'zh' else "◀ -1")
        self.frame_prev_btn.setMinimumSize(QtCore.QSize(80, 30))
        self.frame_prev_btn.setMaximumSize(QtCore.QSize(80, 30))
        self.frame_prev_btn.setCursor(Qt.PointingHandCursor)
        self.frame_prev_btn.setEnabled(False)
        self.frame_prev_btn.clicked.connect(self._on_prev_frame)
        self.frame_prev_btn.setToolTip("向前N帧" if config.defaulelang == 'zh' else "Previous N frames")
        
        # 时间轴滑块
        self.timeline_slider = QSlider(Qt.Horizontal)
        self.timeline_slider.setObjectName("timeline_slider")
        self.timeline_slider.setMinimum(0)
        self.timeline_slider.setMaximum(100)
        self.timeline_slider.setValue(50)
        self.timeline_slider.setEnabled(False)
        self.timeline_slider.setTickPosition(QSlider.TicksBelow)
        self.timeline_slider.setTickInterval(10)
        self.timeline_slider.valueChanged.connect(self._on_timeline_changed)
        
        # 向后N帧按钮
        self.frame_next_btn = QtWidgets.QPushButton()
        self.frame_next_btn.setText("+1帧 ▶" if config.defaulelang == 'zh' else "+1 ▶")
        self.frame_next_btn.setMinimumSize(QtCore.QSize(80, 30))
        self.frame_next_btn.setMaximumSize(QtCore.QSize(80, 30))
        self.frame_next_btn.setCursor(Qt.PointingHandCursor)
        self.frame_next_btn.setEnabled(False)
        self.frame_next_btn.clicked.connect(self._on_next_frame)
        self.frame_next_btn.setToolTip("向后N帧" if config.defaulelang == 'zh' else "Next N frames")
        
        # 总时长标签
        self.timeline_duration_label = QtWidgets.QLabel()
        self.timeline_duration_label.setText("00:00:00")
        self.timeline_duration_label.setMinimumWidth(70)
        self.timeline_duration_label.setAlignment(Qt.AlignCenter)
        
        self.timeline_layout.addWidget(self.timeline_current_label)
        self.timeline_layout.addWidget(self.frame_step_label)
        self.timeline_layout.addWidget(self.frame_step_input)
        self.timeline_layout.addWidget(self.frame_prev_btn)
        self.timeline_layout.addWidget(self.timeline_slider)
        self.timeline_layout.addWidget(self.frame_next_btn)
        self.timeline_layout.addWidget(self.timeline_duration_label)
        
        # 添加刷新预览按钮
        self.preview_layout = QtWidgets.QHBoxLayout()
        self.refresh_preview_btn = QtWidgets.QPushButton()
        self.refresh_preview_btn.setText("刷新预览" if config.defaulelang == 'zh' else "Refresh Preview")
        self.refresh_preview_btn.setMinimumSize(QtCore.QSize(120, 30))
        self.refresh_preview_btn.setCursor(Qt.PointingHandCursor)
        self.refresh_preview_btn.clicked.connect(self._do_update_preview)  # 立即更新，不使用防抖
        self.preview_layout.addStretch()
        self.preview_layout.addWidget(self.refresh_preview_btn)
        self.preview_layout.addStretch()

        # 将预览区域添加到布局
        self.v3.addWidget(self.preview_label)
        self.v3.addLayout(self.timeline_layout)  # 添加时间轴
        self.v3.addLayout(self.preview_layout)
        
        # h3
        self.h3 = QtWidgets.QHBoxLayout()
        self.h3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel()
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(100, 40))
        self.label_4.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.h3.addWidget(self.label_4, 0, QtCore.Qt.AlignTop)

        self.ysphb_videoinput = QtWidgets.QLineEdit()
        self.ysphb_videoinput.setMinimumSize(QtCore.QSize(0, 40))
        self.ysphb_videoinput.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.ysphb_videoinput.setReadOnly(True)
        self.ysphb_videoinput.setObjectName("ysphb_videoinput")
        self.h3.addWidget(self.ysphb_videoinput, 0, QtCore.Qt.AlignTop)

        self.ysphb_selectvideo = QtWidgets.QPushButton()
        self.ysphb_selectvideo.setMinimumSize(QtCore.QSize(150, 40))
        self.ysphb_selectvideo.setObjectName("ysphb_selectvideo")
        self.h3.addWidget(self.ysphb_selectvideo, 0, QtCore.Qt.AlignTop)

        # v3 add h3
        self.v3.addLayout(self.h3)

        # h5
        self.h5 = QtWidgets.QHBoxLayout()
        self.h5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel()
        self.label_5.setMinimumSize(QtCore.QSize(100, 40))
        self.label_5.setObjectName("label_5")
        self.h5.addWidget(self.label_5, 0, QtCore.Qt.AlignTop)

        self.ysphb_wavinput = QtWidgets.QLineEdit()
        self.ysphb_wavinput.setMinimumSize(QtCore.QSize(0, 40))
        self.ysphb_wavinput.setObjectName("ysphb_wavinput")
        self.h5.addWidget(self.ysphb_wavinput, 0, QtCore.Qt.AlignTop)

        self.ysphb_wavinput.textChanged.connect(self.remainraw)

        self.ysphb_selectwav = QtWidgets.QPushButton()
        self.ysphb_selectwav.setMinimumSize(QtCore.QSize(150, 40))
        self.ysphb_selectwav.setObjectName("ysphb_selectwav")
        self.h5.addWidget(self.ysphb_selectwav, 0, QtCore.Qt.AlignTop)
        self.v3.addLayout(self.h5)

        # h6
        self.h6 = QtWidgets.QHBoxLayout()
        self.h6.setObjectName("h6")

        self.label_6 = QtWidgets.QLabel()
        self.label_6.setMinimumSize(QtCore.QSize(100, 40))
        self.label_6.setObjectName("label_6")
        self.h6.addWidget(self.label_6, 0, QtCore.Qt.AlignTop)
        self.ysphb_srtinput = QtWidgets.QLineEdit()
        self.ysphb_srtinput.setMinimumSize(QtCore.QSize(0, 40))
        self.ysphb_srtinput.setObjectName("ysphb_srtinput")
        self.ysphb_srtinput.textChanged.connect(self._on_srt_file_changed)

        self.h6.addWidget(self.ysphb_srtinput, 0, QtCore.Qt.AlignTop)
        self.ysphb_selectsrt = QtWidgets.QPushButton()
        self.ysphb_selectsrt.setMinimumSize(QtCore.QSize(150, 40))
        self.ysphb_selectsrt.setObjectName("ysphb_selectsrt")
        self.h6.addWidget(self.ysphb_selectsrt, 0, QtCore.Qt.AlignTop)

        self.h7 = QtWidgets.QHBoxLayout()
        self.h7.setObjectName("h7")
        self.ysphb_replace = QtWidgets.QCheckBox()
        self.ysphb_replace.setObjectName("ysphb_replace")
        self.ysphb_replace.setDisabled(True)
        self.ysphb_replace.setText(config.transobj['Preserve the original sound in the video'])

        label_audio = QtWidgets.QLabel()
        label_audio.setText("音频时长大于视频时" if config.defaulelang == 'zh' else "Audio duration > video")
        self.audio_process = QtWidgets.QComboBox()
        self.audio_process.addItems([
            "截断" if config.defaulelang == 'zh' else "Truncate",
            "音频加速" if config.defaulelang == 'zh' else "Auto Accelerate",
            "视频末尾定格" if config.defaulelang == 'zh' else "Video copy",
        ])

        self.ysphb_maxlenlabel = QtWidgets.QLabel()
        self.ysphb_maxlenlabel.setText("硬字幕单行字符数")
        self.ysphb_maxlen = QtWidgets.QLineEdit()
        self.ysphb_maxlen.setText('30')

        self.layout_form0 = QtWidgets.QFormLayout()
        self.layout_form0.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ysphb_maxlenlabel)
        self.layout_form0.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ysphb_maxlen)

        self.ysphb_issoft = QtWidgets.QCheckBox()
        self.ysphb_issoft.setObjectName("ysphb_issoft")
        self.ysphb_issoft.setChecked(False)
        self.ysphb_issoft.setText('嵌入软字幕' if config.defaulelang == 'zh' else 'Embedded Soft Subtitles')

        self.layout_form = QtWidgets.QFormLayout()

        self.languagelabel = QtWidgets.QLabel()
        self.languagelabel.setText('软字幕语言' if config.defaulelang == 'zh' else 'soft subtitle language')
        self.languagelabel.setStyleSheet('color:#777')
        self.language = QtWidgets.QComboBox()
        self.language.setMinimumSize(QtCore.QSize(0, 30))
        self.language.setObjectName("language")
        self.language.addItems(config.langnamelist)
        self.language.setDisabled(True)
        self.ysphb_issoft.toggled.connect(self.update_language)

        self.layout_form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.languagelabel)
        self.layout_form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.language)

        self.h7.addWidget(self.ysphb_replace)
        self.h7.addWidget(label_audio)
        self.h7.addWidget(self.audio_process)
        self.h7.addLayout(self.layout_form0)
        self.h7.addStretch()
        self.h7.addWidget(self.ysphb_issoft)
        self.h7.addLayout(self.layout_form)

        self.v3.addLayout(self.h6)
        self.v3.addLayout(self.h7)

        label_position = QtWidgets.QLabel()
        label_position.setText('硬字幕：位置' if config.defaulelang == 'zh' else 'Hard subtitle position')
        self.position = QtWidgets.QComboBox()
        self.position.addItems(list(config.POSTION_ASS_VK.keys()))
        self.position.setToolTip('字幕处于视频中的位置' if config.defaulelang == 'zh' else 'Position of subtitle in video')

        left_label = QtWidgets.QLabel()
        left_label.setText('左边距' if config.defaulelang == 'zh' else 'Margin Left')
        self.marginL = QtWidgets.QLineEdit()
        self.marginL.setText('10')
        self.marginL.setMinimumWidth(50)

        bottom_label = QtWidgets.QLabel()
        bottom_label.setText('垂直边距' if config.defaulelang == 'zh' else 'Margin Vcenter')
        self.marginV = QtWidgets.QLineEdit()
        self.marginV.setText('10')
        self.marginV.setMinimumWidth(50)

        right_label = QtWidgets.QLabel()
        right_label.setText('右边距' if config.defaulelang == 'zh' else 'Margin Right')
        self.marginR = QtWidgets.QLineEdit()
        self.marginR.setText('10')
        self.marginR.setMinimumWidth(50)

        outline_label = QtWidgets.QLabel()
        outline_label.setText('轮廓大小' if config.defaulelang == 'zh' else 'Outline')
        self.outline = QtWidgets.QLineEdit()
        self.outline.setText('1')
        self.outline.setMinimumWidth(50)
        shadow_label = QtWidgets.QLabel()
        shadow_label.setText('阴影大小' if config.defaulelang == 'zh' else 'Shadow')
        self.shadow = QtWidgets.QLineEdit()
        self.shadow.setText('1')
        self.shadow.setMinimumWidth(50)

        fontsize_label = QtWidgets.QLabel()
        fontsize_label.setText('硬字幕：字体大小' if config.defaulelang == 'zh' else 'Font Size')
        self.font_size_edit = QtWidgets.QLineEdit()
        self.font_size_edit.setMinimumWidth(50)
        self.font_size_edit.setText('16')
        self.font_size_edit.setPlaceholderText("字体大小" if config.defaulelang == 'zh' else 'Font Size')
        self.font_size_edit.setToolTip("字体大小" if config.defaulelang == 'zh' else 'Font Size')

        self.font_button = QtWidgets.QPushButton("选择字体" if config.defaulelang == 'zh' else 'Select Fonts')
        self.font_button.setToolTip('点击选择字体' if config.defaulelang == 'zh' else 'Click it for select fonts')
        self.font_button.clicked.connect(self.choose_font)
        self.font_button.setMinimumWidth(150)
        self.font_button.setCursor(Qt.PointingHandCursor)

        self.color_button = QtWidgets.QPushButton("字体颜色" if config.defaulelang == 'zh' else 'Text Colors')
        self.color_button.setCursor(Qt.PointingHandCursor)
        self.color_button.clicked.connect(self.choose_color)
        self.color_button.setMinimumWidth(150)

        self.backgroundcolor_button = QtWidgets.QPushButton(
            "背景阴影色" if config.defaulelang == 'zh' else 'Backgroud Colors')
        self.backgroundcolor_button.setCursor(Qt.PointingHandCursor)
        self.backgroundcolor_button.setMinimumWidth(150)
        self.backgroundcolor_button.clicked.connect(self.choose_backgroundcolor)
        self.backgroundcolor_button.setToolTip(
            '背景色或阴影色，某些播放器下可能不起作用' if config.defaulelang == 'zh' else 'May not work in different players')

        self.bordercolor_button = QtWidgets.QPushButton("轮廓色" if config.defaulelang == 'zh' else 'Border Colors')
        self.bordercolor_button.setCursor(Qt.PointingHandCursor)
        self.bordercolor_button.clicked.connect(self.choose_bordercolor)
        self.bordercolor_button.setToolTip(
            '轮廓描边色，某些播放器下可能不起作用' if config.defaulelang == 'zh' else 'May not work in different players')
        self.bordercolor_button.setMinimumWidth(150)

        # 初始化字体和颜色
        self.selected_font = QFont('Arial', 16)  # 默认字体
        self.selected_color = QColor('#00FFFFFF')  # 默认颜色
        self.selected_backgroundcolor = QColor('#00000000')  # 默认颜色
        self.selected_bordercolor = QColor('#00000000')  # 默认颜色
        
        # 第二语言样式（用于双语字幕）
        self.selected_font_secondary = QFont('Arial', 14)
        self.selected_color_secondary = QColor('#00E0E0E0')  # 浅灰色
        self.selected_backgroundcolor_secondary = QColor('#00000000')
        self.selected_bordercolor_secondary = QColor('#00000000')

        self.ysphb_borderstyle = QtWidgets.QCheckBox()
        self.ysphb_borderstyle.setObjectName("ysphb_borderstyle")
        self.ysphb_borderstyle.setChecked(False)
        self.ysphb_borderstyle.setToolTip(
            '不选中表示有轮廓描边阴影但无背景色块，选中则相反' if config.defaulelang == 'zh' else 'Unchecked means there is an outline stroke shadow but no background color block, and the opposite is true if checked')
        self.ysphb_borderstyle.setText('背景色块风格' if config.defaulelang == 'zh' else 'Background color area Style')

        format_layout = QHBoxLayout()
        format_layout.setAlignment(Qt.AlignmentFlag.AlignLeft)

        format_layout.addWidget(label_position)
        format_layout.addWidget(self.position)
        format_layout.addStretch()
        format_layout.addWidget(left_label)
        format_layout.addWidget(self.marginL)
        format_layout.addStretch()
        format_layout.addWidget(bottom_label)
        format_layout.addWidget(self.marginV)
        format_layout.addStretch()
        format_layout.addWidget(right_label)
        format_layout.addWidget(self.marginR)
        format_layout.addStretch()
        format_layout.addWidget(outline_label)
        format_layout.addWidget(self.outline)
        format_layout.addStretch()
        format_layout.addWidget(shadow_label)
        format_layout.addWidget(self.shadow)

        format_layout2 = QHBoxLayout()
        format_layout2.setAlignment(Qt.AlignmentFlag.AlignLeft)

        # 添加第一语言标签
        first_lang_label = QtWidgets.QLabel()
        first_lang_label.setText('第一语言:' if config.defaulelang == 'zh' else '1st Language:')
        first_lang_label.setStyleSheet("font-weight: bold; color: #4CAF50;")
        
        format_layout2.addWidget(first_lang_label)
        format_layout2.addWidget(fontsize_label)
        format_layout2.addWidget(self.font_size_edit)
        format_layout2.addStretch()
        format_layout2.addWidget(self.font_button)
        format_layout2.addWidget(self.color_button)
        format_layout2.addWidget(self.backgroundcolor_button)
        format_layout2.addWidget(self.bordercolor_button)
        format_layout2.addWidget(self.ysphb_borderstyle)

        # 双语字幕开关
        self.bilingual_subtitle_checkbox = QtWidgets.QCheckBox()
        self.bilingual_subtitle_checkbox.setText('启用双语字幕样式' if config.defaulelang == 'zh' else 'Enable Bilingual Subtitle')
        self.bilingual_subtitle_checkbox.setToolTip(
            '勾选后可为双语字幕的第二行文本设置不同样式' if config.defaulelang == 'zh' 
            else 'Enable different styles for the second line in bilingual subtitles')
        self.bilingual_subtitle_checkbox.stateChanged.connect(self._toggle_secondary_style)
        
        # 调换顺序复选框
        self.swap_subtitle_order_checkbox = QtWidgets.QCheckBox()
        self.swap_subtitle_order_checkbox.setText('调换顺序(第二语言在上)' if config.defaulelang == 'zh' else 'Swap Order (2nd on top)')
        self.swap_subtitle_order_checkbox.setToolTip(
            '勾选后第二语言显示在上方，第一语言显示在下方' if config.defaulelang == 'zh' 
            else 'When checked, the second language displays on top, first language on bottom')
        self.swap_subtitle_order_checkbox.stateChanged.connect(lambda: self.update_subtitle_preview())
        
        bilingual_layout = QHBoxLayout()
        bilingual_layout.addWidget(self.bilingual_subtitle_checkbox)
        bilingual_layout.addWidget(self.swap_subtitle_order_checkbox)
        bilingual_layout.addStretch()
        
        # 第二语言样式控件
        fontsize_label_sec = QtWidgets.QLabel()
        fontsize_label_sec.setText('字体大小' if config.defaulelang == 'zh' else 'Font Size')
        self.font_size_edit_secondary = QtWidgets.QLineEdit()
        self.font_size_edit_secondary.setMinimumWidth(50)
        self.font_size_edit_secondary.setText('14')
        self.font_size_edit_secondary.setPlaceholderText("字体大小" if config.defaulelang == 'zh' else 'Font Size')
        self.font_size_edit_secondary.setToolTip("第二语言字体大小" if config.defaulelang == 'zh' else 'Secondary Font Size')
        
        self.font_button_secondary = QtWidgets.QPushButton("选择字体" if config.defaulelang == 'zh' else 'Select Fonts')
        self.font_button_secondary.setToolTip('第二语言字体' if config.defaulelang == 'zh' else 'Secondary font')
        self.font_button_secondary.clicked.connect(self.choose_font_secondary)
        self.font_button_secondary.setMinimumWidth(150)
        self.font_button_secondary.setCursor(Qt.PointingHandCursor)
        
        self.color_button_secondary = QtWidgets.QPushButton("字体颜色" if config.defaulelang == 'zh' else 'Text Colors')
        self.color_button_secondary.setCursor(Qt.PointingHandCursor)
        self.color_button_secondary.clicked.connect(self.choose_color_secondary)
        self.color_button_secondary.setMinimumWidth(150)
        
        self.backgroundcolor_button_secondary = QtWidgets.QPushButton(
            "背景阴影色" if config.defaulelang == 'zh' else 'Background Colors')
        self.backgroundcolor_button_secondary.setCursor(Qt.PointingHandCursor)
        self.backgroundcolor_button_secondary.setMinimumWidth(150)
        self.backgroundcolor_button_secondary.clicked.connect(self.choose_backgroundcolor_secondary)
        
        self.bordercolor_button_secondary = QtWidgets.QPushButton("轮廓色" if config.defaulelang == 'zh' else 'Border Colors')
        self.bordercolor_button_secondary.setCursor(Qt.PointingHandCursor)
        self.bordercolor_button_secondary.clicked.connect(self.choose_bordercolor_secondary)
        self.bordercolor_button_secondary.setMinimumWidth(150)
        
        format_layout3 = QHBoxLayout()
        format_layout3.setAlignment(Qt.AlignmentFlag.AlignLeft)
        
        # 添加第二语言标签
        second_lang_label = QtWidgets.QLabel()
        second_lang_label.setText('第二语言:' if config.defaulelang == 'zh' else '2nd Language:')
        second_lang_label.setStyleSheet("font-weight: bold; color: #FF9800;")
        
        format_layout3.addWidget(second_lang_label)
        format_layout3.addWidget(fontsize_label_sec)
        format_layout3.addWidget(self.font_size_edit_secondary)
        format_layout3.addStretch()
        format_layout3.addWidget(self.font_button_secondary)
        format_layout3.addWidget(self.color_button_secondary)
        format_layout3.addWidget(self.backgroundcolor_button_secondary)
        format_layout3.addWidget(self.bordercolor_button_secondary)
        
        # 将第二语言控件存储起来，方便显示/隐藏
        self.secondary_widgets = [
            second_lang_label, fontsize_label_sec, self.font_size_edit_secondary,
            self.font_button_secondary, self.color_button_secondary,
            self.backgroundcolor_button_secondary, self.bordercolor_button_secondary
        ]
        
        # 初始隐藏第二语言控件
        for widget in self.secondary_widgets:
            widget.setVisible(False)

        self.v3.addLayout(format_layout)
        self.v3.addLayout(format_layout2)
        self.v3.addLayout(bilingual_layout)
        self.v3.addLayout(format_layout3)

        self.ysphb_startbtn = QtWidgets.QPushButton()
        self.ysphb_startbtn.setMinimumSize(QtCore.QSize(250, 40))
        self.ysphb_startbtn.setObjectName("ysphb_startbtn")
        self.v3.addWidget(self.ysphb_startbtn)
        self.v3.addStretch()

        self.h8 = QtWidgets.QHBoxLayout()
        self.h8.setObjectName("horizontalLayout_20")
        self.ysphb_out = QtWidgets.QLineEdit()
        self.ysphb_out.setMinimumSize(QtCore.QSize(0, 30))
        self.ysphb_out.setReadOnly(True)
        self.ysphb_out.setObjectName("ysphb_out")
        self.h8.addWidget(self.ysphb_out)
        self.ysphb_opendir = QtWidgets.QPushButton()
        self.ysphb_opendir.setMinimumSize(QtCore.QSize(0, 30))
        self.ysphb_opendir.setObjectName("ysphb_opendir")
        self.h8.addWidget(self.ysphb_opendir)
        self.v3.addLayout(self.h8)

        # end
        self.horizontalLayout_3.addLayout(self.v3)

        self.retranslateUi(vasrt)
        
        # 连接所有字幕参数控件到预览更新
        self.position.currentTextChanged.connect(lambda: self.update_subtitle_preview())
        self.marginL.textChanged.connect(lambda: self.update_subtitle_preview())
        self.marginV.textChanged.connect(lambda: self.update_subtitle_preview())
        self.marginR.textChanged.connect(lambda: self.update_subtitle_preview())
        self.outline.textChanged.connect(lambda: self.update_subtitle_preview())
        self.shadow.textChanged.connect(lambda: self.update_subtitle_preview())
        self.font_size_edit.textChanged.connect(lambda: self.update_subtitle_preview())
        self.font_size_edit_secondary.textChanged.connect(lambda: self.update_subtitle_preview())  # 第二语言字号输入监听
        self.ysphb_borderstyle.toggled.connect(lambda: self.update_subtitle_preview())

        QMetaObject.connectSlotsByName(vasrt)

    def qcolor_to_ass_color(self, color, type='fc'):
        # 获取颜色的 RGB 值
        r = color.red()
        g = color.green()
        b = color.blue()
        a = color.alpha()
        if type in ['bg', 'bd']:
            return f"&H{a:02X}{b:02X}{g:02X}{r:02X}".upper()
        # 将 RGBA 转换为 ASS 的颜色格式 &HBBGGRR

        return f"&H{a:02X}{b:02X}{g:02X}{r:02X}".upper()
        # return f"&H{b:02X}{g:02X}{r:02X}"

    def _toggle_secondary_style(self, state):
        """切换第二语言样式控件的显示/隐藏"""
        is_visible = (state == Qt.CheckState.Checked.value)
        for widget in self.secondary_widgets:
            widget.setVisible(is_visible)
        self.update_subtitle_preview()
    
    def choose_font(self):
        dialog = QFontDialog(self.selected_font, self)
        if dialog.exec():
            font = dialog.selectedFont()
            font_name = font.family()
            font_size = font.pointSize()
            self.selected_font = font
            self.font_size_edit.setText(str(font_size))
            self.font_button.setText(font_name)
            self._setfont()
            self.update_subtitle_preview()
    
    def choose_font_secondary(self):
        """选择第二语言字体"""
        dialog = QFontDialog(self.selected_font_secondary, self)
        dialog.setWindowTitle('选择第二语言字体' if config.defaulelang == 'zh' else 'Select Secondary Font')
        if dialog.exec():
            font = dialog.selectedFont()
            font_size = font.pointSize()
            self.selected_font_secondary = font
            self.font_size_edit_secondary.setText(str(font_size))
            self.update_subtitle_preview()

    def _setfont(self):
        bgcolor_name = self.selected_backgroundcolor.name()
        bgcolor = '' if self.selected_backgroundcolor.alpha() == 255 else f'background-color:{bgcolor_name}'
        bdcolor_name = self.selected_bordercolor.name()
        bdcolor = '' if self.selected_bordercolor.alpha() == 255 else f'border:1px solid {bdcolor_name}'

        # color_name = self.selected_color.name()
        def blend_colors(selected_color: QColor, bgcolor_name: str) -> str:
            bg_color = QColor(bgcolor_name)
            # Invert alpha: 0 = solid color, 255 = transparent
            inv_alpha = 1.0 - (selected_color.alpha() / 255.0)

            r = int(selected_color.red() * inv_alpha + bg_color.red() * (1 - inv_alpha))
            g = int(selected_color.green() * inv_alpha + bg_color.green() * (1 - inv_alpha))
            b = int(selected_color.blue() * inv_alpha + bg_color.blue() * (1 - inv_alpha))
            # For CSS alpha: 0 (transparent) when selected_color.alpha()==255, 1 (opaque) when ==0
            css_alpha = inv_alpha

            return f'rgba({r}, {g}, {b}, {css_alpha:.2f})'

        # color = f'color:{bgcolor_name}' if self.selected_color.alpha()  == 255 else f'color:{color_name}'
        color_name = blend_colors(self.selected_color, bgcolor_name)
        color = f'color:{color_name}'
        font = self.selected_font
        button_style = f"""font-family:'{font.family()}';font-size:{font.pointSize()}px;font-weight:{700 if font.bold() else 400};font-style:{'italic' if font.italic() else 'normal'};{bgcolor};{color};{bdcolor}"""
        self.font_button.setStyleSheet(button_style)

    def choose_color(self):
        color = self.selected_color
        color.setAlpha(0)  # Set default alpha to 0 (fully opaque)
        dialog = QColorDialog(color, self)
        dialog.setOption(QColorDialog.ShowAlphaChannel, True)  # 启用透明度选择
        dialog.exec()  # or dialog.open()
        color = dialog.currentColor()
        if color.isValid():
            self.selected_color = color
            self._setfont()
            self.update_subtitle_preview()
    
    def choose_color_secondary(self):
        """选择第二语言字体颜色"""
        color = self.selected_color_secondary
        color.setAlpha(0)
        dialog = QColorDialog(color, self)
        dialog.setWindowTitle('选择第二语言字体颜色' if config.defaulelang == 'zh' else 'Select Secondary Text Color')
        dialog.setOption(QColorDialog.ShowAlphaChannel, True)
        dialog.exec()
        color = dialog.currentColor()
        if color.isValid():
            self.selected_color_secondary = color
            self.update_subtitle_preview()

    def choose_backgroundcolor(self):
        color = self.selected_backgroundcolor
        color.setAlpha(0)  # Set default alpha to 0 (fully opaque)
        dialog = QColorDialog(color, self)
        dialog.setOption(QColorDialog.ShowAlphaChannel, True)  # 启用透明度选择

        dialog.exec()  # or dialog.open() to show non-model dialog to enable alpha setting
        color = dialog.currentColor()

        if color.isValid():
            self.selected_backgroundcolor = color
            self._setfont()
            self.update_subtitle_preview()
    
    def choose_backgroundcolor_secondary(self):
        """选择第二语言背景色"""
        color = self.selected_backgroundcolor_secondary
        color.setAlpha(0)
        dialog = QColorDialog(color, self)
        dialog.setWindowTitle('选择第二语言背景色' if config.defaulelang == 'zh' else 'Select Secondary Background Color')
        dialog.setOption(QColorDialog.ShowAlphaChannel, True)
        dialog.exec()
        color = dialog.currentColor()
        if color.isValid():
            self.selected_backgroundcolor_secondary = color
            self.update_subtitle_preview()

    def choose_bordercolor(self):
        color = self.selected_bordercolor
        dialog = QColorDialog(color, self)
        dialog.setOption(QColorDialog.ShowAlphaChannel, True)  # 启用透明度选择

        dialog.exec()  # or dialog.open()
        color = dialog.currentColor()
        if color.isValid():
            self.selected_bordercolor = color
            self._setfont()
            self.update_subtitle_preview()
    
    def choose_bordercolor_secondary(self):
        """选择第二语言轮廓色"""
        color = self.selected_bordercolor_secondary
        dialog = QColorDialog(color, self)
        dialog.setWindowTitle('选择第二语言轮廓色' if config.defaulelang == 'zh' else 'Select Secondary Border Color')
        dialog.setOption(QColorDialog.ShowAlphaChannel, True)
        dialog.exec()
        color = dialog.currentColor()
        if color.isValid():
            self.selected_bordercolor_secondary = color
            self.update_subtitle_preview()

    def remainraw(self, t):
        if Path(t).is_file():
            self.ysphb_replace.setDisabled(False)
            self.ysphb_replace.setChecked(True)
        else:
            self.ysphb_replace.setChecked(False)
            self.ysphb_replace.setDisabled(True)

    def update_language(self, state):
        self.languagelabel.setStyleSheet(f"""color:#f1f1f1""" if state else 'color:#777777')
        self.language.setDisabled(False if state else True)

        self.font_button.setDisabled(True if state else False)
        self.font_size_edit.setDisabled(True if state else False)
        self.color_button.setDisabled(True if state else False)
        self.backgroundcolor_button.setDisabled(True if state else False)
        self.bordercolor_button.setDisabled(True if state else False)
        
        # 更新预览
        self.update_subtitle_preview()
    
    def _get_frame_step(self):
        """获取用户设置的帧数步进值"""
        try:
            step = int(self.frame_step_input.text())
            # 限制在1-100之间
            return max(1, min(step, 100))
        except:
            return 1
    
    def _update_frame_buttons_text(self):
        """更新按钮文本显示当前帧数"""
        step = self._get_frame_step()
        if config.defaulelang == 'zh':
            self.frame_prev_btn.setText(f"◀ -{step}帧")
            self.frame_next_btn.setText(f"+{step}帧 ▶")
        else:
            self.frame_prev_btn.setText(f"◀ -{step}")
            self.frame_next_btn.setText(f"+{step} ▶")
    
    def _on_prev_frame(self):
        """向前N帧"""
        step = self._get_frame_step()
        self._adjust_frame(-step)
    
    def _on_next_frame(self):
        """向后N帧"""
        step = self._get_frame_step()
        self._adjust_frame(step)
    
    def _adjust_frame(self, frame_count):
        """微调帧数
        frame_count: 正数向后，负数向前（帧数）
        """
        if not self.current_video_path or self.video_duration_ms == 0:
            return
        
        # 计算一帧的时长（毫秒）
        frame_duration_ms = 1000 / self.video_fps
        
        # 计算新的时间位置
        new_time_ms = self.current_time_ms + (frame_count * frame_duration_ms)
        
        # 限制在视频范围内
        new_time_ms = max(0, min(new_time_ms, self.video_duration_ms))
        
        # 更新当前时间
        self.current_time_ms = new_time_ms
        
        # 更新时间标签
        self._update_time_label(int(new_time_ms))
        
        # 提取新的视频帧
        self._extract_frame_at_time(int(new_time_ms))
        
        # 同步滑块位置（不触发valueChanged信号）
        if self.video_duration_ms > 0:
            slider_value = int(new_time_ms * 100 / self.video_duration_ms)
            self.timeline_slider.blockSignals(True)
            self.timeline_slider.setValue(slider_value)
            self.timeline_slider.blockSignals(False)
    
    def _on_timeline_changed(self, value):
        """时间轴滑块改变时的处理"""
        if not self.current_video_path or self.video_duration_ms == 0:
            return
        
        # 计算当前时间位置（毫秒）
        current_time_ms = int(self.video_duration_ms * value / 100)
        
        # 保存当前时间
        self.current_time_ms = current_time_ms
        
        # 更新时间标签
        self._update_time_label(current_time_ms)
        
        # 提取新的视频帧
        self._extract_frame_at_time(current_time_ms)
    
    def _update_time_label(self, time_ms):
        """更新时间标签显示"""
        seconds = time_ms / 1000
        hours = int(seconds // 3600)
        minutes = int((seconds % 3600) // 60)
        secs = int(seconds % 60)
        time_str = f"{hours:02d}:{minutes:02d}:{secs:02d}"
        self.timeline_current_label.setText(time_str)
    
    def _extract_frame_at_time(self, time_ms):
        """提取指定时间点的视频帧"""
        if not self.current_video_path:
            return
        
        try:
            import time
            from videotrans.util import tools
            from PySide6.QtGui import QPixmap
            from PySide6.QtCore import Qt
            
            # 转换为秒
            seek_time = time_ms / 1000
            
            # 生成临时文件路径
            frame_path = config.TEMP_HOME + f"/video_frame_{time.time()}.jpg"
            
            # 使用ffmpeg截取视频帧
            cmd = [
                '-y',
                '-ss', str(seek_time),
                '-i', self.current_video_path,
                '-vframes', '1',
                '-q:v', '2',
                frame_path
            ]
            tools.runffmpeg(cmd)
            
            # 如果截取成功，更新预览
            if Path(frame_path).exists():
                # 删除旧的视频帧文件
                if self.video_frame_path and Path(self.video_frame_path).exists():
                    try:
                        import os
                        os.remove(self.video_frame_path)
                    except:
                        pass
                
                self.video_frame_path = frame_path
                pixmap = QPixmap(frame_path)
                if not pixmap.isNull():
                    scaled_pixmap = pixmap.scaled(self.preview_label.size(), Qt.KeepAspectRatio, Qt.SmoothTransformation)
                    self.preview_label.setPixmap(scaled_pixmap)
                    self.preview_label.setText("")
                    
                    # 触发字幕预览更新
                    self.update_subtitle_preview()
        except Exception as e:
            print(f"提取视频帧失败: {e}")
    
    def _on_srt_file_changed(self, srt_path):
        """字幕文件路径改变时的处理"""
        if not srt_path or not Path(srt_path).exists():
            self.subtitle_list = []
            self.current_srt_path = None
            return
        
        # 只有真正的srt文件才加载
        if not srt_path.endswith('.srt'):
            return
            
        try:
            from videotrans.util import tools
            # 加载字幕列表
            self.subtitle_list = tools.get_subtitle_from_srt(srt_path, is_file=True)
            self.current_srt_path = srt_path
            print(f"成功加载字幕文件，共 {len(self.subtitle_list)} 条字幕")
            # 更新预览
            self.update_subtitle_preview()
        except Exception as e:
            print(f"加载字幕文件失败: {e}")
            self.subtitle_list = []
            self.current_srt_path = None
    
    def _get_subtitle_at_time(self, time_ms):
        """获取指定时间点的字幕文本"""
        if not self.subtitle_list:
            # 没有字幕文件，返回示例文本
            return "这是字幕预览效果\nSubtitle Preview Effect"
        
        # 查找当前时间点对应的字幕
        for sub in self.subtitle_list:
            if sub['start_time'] <= time_ms <= sub['end_time']:
                return sub['text']
        
        # 当前时间点没有字幕，返回空字符串或提示
        return ""  # 或者返回 "[当前时间无字幕]"
    
    def update_subtitle_preview(self):
        """更新字幕预览（使用防抖）"""
        # 停止之前的定时器
        self.preview_update_timer.stop()
        # 延迟500毫秒后执行更新
        self.preview_update_timer.start(500)
    
    def _do_update_preview(self):
        """实际执行预览更新"""
        if not self.video_frame_path or not Path(self.video_frame_path).exists():
            return
        
        # 如果是软字幕，不显示预览效果
        if self.ysphb_issoft.isChecked():
            pixmap = QPixmap(self.video_frame_path)
            if not pixmap.isNull():
                scaled_pixmap = pixmap.scaled(self.preview_label.size(), Qt.KeepAspectRatio, Qt.SmoothTransformation)
                self.preview_label.setPixmap(scaled_pixmap)
            return
            
        try:
            import time
            from videotrans.util import tools
            
            # 获取当前时间点的字幕文本
            subtitle_text = self._get_subtitle_at_time(self.current_time_ms)
            
            # 如果没有字幕文本，直接显示原视频帧
            if not subtitle_text:
                pixmap = QPixmap(self.video_frame_path)
                if not pixmap.isNull():
                    scaled_pixmap = pixmap.scaled(self.preview_label.size(), Qt.KeepAspectRatio, Qt.SmoothTransformation)
                    self.preview_label.setPixmap(scaled_pixmap)
                return
            
            # 创建临时字幕文件用于预览
            preview_srt = config.TEMP_HOME + f"/preview_{time.time()}.srt"
            preview_text = f"1\n00:00:00,000 --> 00:00:05,000\n{subtitle_text}\n\n"
            
            with open(preview_srt, 'w', encoding='utf-8') as f:
                f.write(preview_text)
            
            # 创建ASS文件
            preview_ass = config.TEMP_HOME + f"/preview_{time.time()}.ass"
            self._create_preview_ass(preview_srt, preview_ass)
            
            # 使用ffmpeg将字幕绘制到视频帧上
            preview_output = config.TEMP_HOME + f"/preview_{time.time()}.jpg"
            import os
            os.chdir(config.TEMP_HOME)
            
            cmd = [
                '-y',
                '-i', self.video_frame_path,
                '-vf', f"subtitles={os.path.basename(preview_ass)}:charenc=utf-8",
                '-frames:v', '1',
                preview_output
            ]
            tools.runffmpeg(cmd)
            
            # 显示预览图片
            if Path(preview_output).exists():
                pixmap = QPixmap(preview_output)
                if not pixmap.isNull():
                    scaled_pixmap = pixmap.scaled(self.preview_label.size(), Qt.KeepAspectRatio, Qt.SmoothTransformation)
                    self.preview_label.setPixmap(scaled_pixmap)
                
                # 清理临时文件
                try:
                    os.remove(preview_output)
                except:
                    pass
            
            # 清理临时字幕文件
            try:
                os.remove(preview_srt)
                os.remove(preview_ass)
            except:
                pass
                
        except Exception as e:
            print(f"更新预览失败: {e}")
    
    def _create_preview_ass(self, srt_file, ass_file):
        """创建预览用的ASS文件"""
        from videotrans.util import tools
        
        with open(ass_file, 'w', encoding='utf-8') as file:
            stem = Path(srt_file).stem
            file.write("[Script Info]\n")
            file.write(f"Title: {stem}\n")
            file.write(f"Original Script: {stem}\n")
            file.write("ScriptType: v4.00+\n")
            file.write("PlayResX: 384\nPlayResY: 288\n")
            file.write("ScaledBorderAndShadow: yes\n")
            file.write("YCbCr Matrix: None\n")
            file.write("\n[V4+ Styles]\n")
            file.write(
                f"Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n")
            
            left = self.marginL.text() if self.marginL.text() else '10'
            right = self.marginR.text() if self.marginR.text() else '10'
            vbottom = self.marginV.text() if self.marginV.text() else '10'
            align = config.POSTION_ASS_VK.get(self.position.currentText(), 2)
            shadow = self.shadow.text() if self.shadow.text() else '1'
            outline = self.outline.text() if self.outline.text() else '1'
            
            bgcolor = self.qcolor_to_ass_color(self.selected_backgroundcolor, type='bg')
            bdcolor = self.qcolor_to_ass_color(self.selected_bordercolor, type='bd')
            
            if self.ysphb_borderstyle.isChecked():
                bdcolor = bgcolor
            fontcolor = self.qcolor_to_ass_color(self.selected_color, type='fc')
            
            font_size = self.font_size_edit.text() if self.font_size_edit.text() else "16"
            
            # 写入默认样式（第一行文本）
            file.write(
                f'Style: Default,{self.selected_font.family()},{font_size},{fontcolor},{fontcolor},{bdcolor},{bgcolor},{int(self.selected_font.bold())},{int(self.selected_font.italic())},0,0,100,100,0,0,{3 if self.ysphb_borderstyle.isChecked() else 1},{outline},{shadow},{align},{left},{right},{vbottom},1\n')
            
            # 检测是否为双语字幕
            srt_list = tools.get_subtitle_from_srt(srt_file, is_file=True)
            is_bilingual = any('\n' in it['text'] for it in srt_list)
            
            # 如果是双语字幕或勾选了双语样式，添加第二种样式（第二行文本）
            use_bilingual_style = is_bilingual or self.bilingual_subtitle_checkbox.isChecked()
            if use_bilingual_style:
                # 使用GUI配置的第二语言样式
                fontcolor_sec = self.qcolor_to_ass_color(self.selected_color_secondary, type='fc')
                bdcolor_sec = self.qcolor_to_ass_color(self.selected_bordercolor_secondary, type='bd')
                bgcolor_sec = self.qcolor_to_ass_color(self.selected_backgroundcolor_secondary, type='bg')
                
                fontname_sec = self.selected_font_secondary.family()
                fontsize_sec = self.font_size_edit_secondary.text() if self.font_size_edit_secondary.text() else "14"
                outline_sec = outline
                shadow_sec = shadow
                borderstyle_sec = 3 if self.ysphb_borderstyle.isChecked() else 1
                
                file.write(
                    f'Style: Secondary,{fontname_sec},{fontsize_sec},{fontcolor_sec},{fontcolor_sec},{bdcolor_sec},{bgcolor_sec},0,0,0,0,100,100,0,0,{borderstyle_sec},{outline_sec},{shadow_sec},{align},{left},{right},{vbottom},1\n')
            
            file.write("\n[Events]\n")
            file.write("Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n")
            
            for it in srt_list:
                start_str = self._format_milliseconds(it['start_time'])
                end_str = self._format_milliseconds(it['end_time'])
                text = it['text'].replace("\n", "\\N")
                
                # 如果是双语字幕，为两行文本分别指定样式
                if is_bilingual and '\\N' in text:
                    lines = text.split('\\N', 1)
                    if len(lines) == 2:
                        # 根据是否勾选"调换顺序"来决定上下顺序
                        if self.swap_subtitle_order_checkbox.isChecked():
                            # 第二语言在上，第一语言在下
                            text = f"{{\\rSecondary}}{lines[1].strip()}\\N{{\\rDefault}}{lines[0].strip()}"
                        else:
                            # 第一语言在上，第二语言在下（默认）
                            text = f"{{\\rDefault}}{lines[0].strip()}\\N{{\\rSecondary}}{lines[1].strip()}"
                
                file.write(f"Dialogue: 0,{start_str},{end_str},Default,,0,0,0,,{text}\n")
    
    def _format_milliseconds(self, milliseconds):
        """将毫秒数转换为 HH:mm:ss.zz 格式的字符串"""
        seconds = milliseconds / 1000
        minutes, seconds = divmod(seconds, 60)
        hours, minutes = divmod(minutes, 60)
        milliseconds_part = int((seconds * 1000) % 1000) // 10
        
        formatted_hours = f"{int(hours):02}"
        formatted_minutes = f"{int(minutes):02}"
        formatted_seconds = f"{int(seconds):02}"
        formatted_milliseconds = f"{milliseconds_part:02}"
        
        return f"{formatted_hours}:{formatted_minutes}:{formatted_seconds}.{formatted_milliseconds}"

    def retranslateUi(self, vasrt):
        vasrt.setWindowTitle("视频、音频、字幕三者合并" if config.defaulelang == 'zh' else 'Video, audio, and subtitle merging')

        self.label_4.setText('视频文件' if config.defaulelang == 'zh' else 'Video')
        self.label_5.setText('音频文件' if config.defaulelang == 'zh' else 'Audio')
        self.label_6.setText('字幕文件/srt' if config.defaulelang == 'zh' else 'Subtitles/srt')
        self.ysphb_selectvideo.setText('选择视频文件' if config.defaulelang == 'zh' else 'Select a Video')
        self.ysphb_videoinput.setPlaceholderText('选择视频文件' if config.defaulelang == 'zh' else 'Select a Video')
        self.ysphb_selectwav.setText('选择音频文件' if config.defaulelang == 'zh' else 'Select a Audio')
        self.ysphb_wavinput.setPlaceholderText('选择音频文件' if config.defaulelang == 'zh' else 'Select a Audio')
        self.ysphb_selectsrt.setText('选择srt字幕文件' if config.defaulelang == 'zh' else 'Select a Srt file')
        self.ysphb_srtinput.setPlaceholderText('选择srt字幕文件' if config.defaulelang == 'zh' else 'Select a Srt file')
        self.ysphb_startbtn.setText('开始执行' if config.defaulelang == 'zh' else 'Start operating')
        self.ysphb_opendir.setText('打开结果目录' if config.defaulelang == 'zh' else 'Open the results catalog')
